Repository Lakshya2610/Findr, pull requests merged in 2020-08, with the labels that each got.

#130 Image Support
  .DS_Store
  app/android/app/src/main/assets/fonts/AntDesign.ttf
  app/android/app/src/main/assets/fonts/Entypo.ttf
  app/android/app/src/main/assets/fonts/EvilIcons.ttf
  app/android/app/src/main/assets/fonts/Feather.ttf
  app/android/app/src/main/assets/fonts/FontAwesome.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  app/android/app/src/main/assets/fonts/Fontisto.ttf
  app/android/app/src/main/assets/fonts/Foundation.ttf
  app/android/app/src/main/assets/fonts/Ionicons.ttf
  app/android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  app/android/app/src/main/assets/fonts/MaterialIcons.ttf
  app/android/app/src/main/assets/fonts/Octicons.ttf
  app/android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  app/android/app/src/main/assets/fonts/Zocial.ttf
  app/android/app/src/main/assets/fonts/tinderclone.ttf
  app/android/gradle.properties
  app/assets/data/APIConnection.js
  app/containers/Chat.js
  app/ios/Findr.xcodeproj/project.pbxproj
  app/ios/Findr/Images.xcassets/AppIcon.appiconset/Contents.json
  app/ios/Findr/Info.plist
Labels: Beta, Front-end Logic

#138 Splash screen
  app/AccApp.js
  app/App.js
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-hdpi/splash_icon.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-mdpi/splash_icon.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xhdpi/splash_icon.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xxhdpi/splash_icon.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/android/app/src/main/res/mipmap-xxxhdpi/splash_icon.png
  app/assets/styles/index.js
  app/containers/SplashScreen.js
Labels: Beta, Front-end Logic

#137 Pending matches
  app/assets/data/APIConnection.js
  app/containers/Matches.js
Labels: Front-end Logic, bug

#149 Fixed SplashScreen
  app/containers/SplashScreen.js
Labels: Beta, Front-end Logic

#152 Profile page bug fixed
  app/assets/styles/index.js
  app/components/ProfileItem.js
  app/components/TagClubs.js
  app/components/TagCourses.js
  app/containers/SignUp.js
Labels: Beta, Front-end Logic

#150 Updated textbox colors on signup page
  app/assets/styles/index.js
  app/containers/SignUp.js
Labels: Beta, UI

#154 Bug fixes for beta
  app/android/gradle.properties
  app/assets/images/placeholder.png
  app/assets/styles/index.js
  app/components/CachedImage.js
  app/components/ProfileItem.js
  app/containers/Home.js
  app/containers/Matches.js
  app/containers/Profile.js
Labels: Beta, Front-end Logic, UI

#153 Final CSS done
  app/assets/styles/index.js
  app/containers/SignUp.js
  app/containers/Verifiy.js
Labels: Beta, UI

#151 Multi Image Picker + Cropper
  .DS_Store
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/assets/fonts/AntDesign.ttf
  app/android/app/src/main/assets/fonts/Entypo.ttf
  app/android/app/src/main/assets/fonts/EvilIcons.ttf
  app/android/app/src/main/assets/fonts/Feather.ttf
  app/android/app/src/main/assets/fonts/FontAwesome.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  app/android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  app/android/app/src/main/assets/fonts/Foundation.ttf
  app/android/app/src/main/assets/fonts/Ionicons.ttf
  app/android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  app/android/app/src/main/assets/fonts/MaterialIcons.ttf
  app/android/app/src/main/assets/fonts/Octicons.ttf
  app/android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  app/android/app/src/main/assets/fonts/Zocial.ttf
  app/android/app/src/main/assets/fonts/tinderclone.ttf
  app/android/app/src/main/assets/index.android.bundle
  app/android/app/src/main/java/com/findr/MainApplication.java
  app/android/build.gradle
  app/android/gradle.properties
  app/android/settings.gradle
  app/assets/icons/camera.svg
  app/containers/Chat.js
  app/containers/Messages.js
  app/containers/Profile.js
  app/ios/Findr.xcodeproj/project.pbxproj
  app/ios/Findr/Info.plist
  app/package-lock.json
  app/package.json
Labels: Front-end Logic, UI

#161 Major Bugfixes for beta release
  app/AccApp.js
  app/android/gradle.properties
  app/components/MatchPopup.js
  app/components/ProfilePopup.js
  app/components/TagClubs.js
  app/components/TagCourses.js
  app/containers/Home.js
  app/containers/LogIn.js
  app/containers/Matches.js
  app/containers/Messages.js
  app/containers/Onboarding.js
  app/containers/OtherProfile.js
  app/containers/OtherProfile2.js
  app/containers/Profile.js
  app/containers/SignUp.js
  app/package-lock.json
Labels: Front-end Logic, UI

#165 HTTPS Support for the API
  backend/index.js
  dev-server-config/main.tf
  dev-server-config/variables.tf
Labels: Backend, Server Infrastructure

#164 Profile page redesign
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/assets/index.android.bundle
  app/android/gradle.properties
  app/assets/data/APIConnection.js
  app/assets/icons/cross.svg
  app/assets/icons/menu_icon.svg
  app/assets/styles/index.js
  app/components/OutOfCardsPopup.js
  app/components/ProfilePageComponents/BasicInfo.js
  app/components/ProfilePageComponents/Header.js
  app/components/ProfilePageComponents/InfoContainer.js
  app/components/ProfilePageComponents/KeyValue.js
  app/components/ProfilePageComponents/List.js
  app/components/ProfilePageComponents/ListItem.js
  app/components/ProfilePageComponents/ProfilePicture.js
  app/components/ProfilePageComponents/Tag.js
  app/components/Tag.js
  app/components/TagClubs.js
  app/components/TagCourses.js
  app/containers/LogIn.js
  app/containers/Onboarding.js
  app/containers/OtherProfile2.js
  app/containers/Profile.js
  app/containers/SignUp.js
Labels: Beta, Front-end Logic, UI

#166 Added separate route for health check for the Load Balancer
  backend/index.js
  dev-server-config/main.tf
Labels: Backend, Server Infrastructure

#171 Verification successful page
  backend/index.js
  backend/public/logo.svg
  backend/public/verify.html
Labels: Backend, enhancement

#173 Socket.io-redis integration
  .github/workflows/backend.yml
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/utils/Chat.js
Labels: Backend, enhancement
